### ISSUE TITLE
Demo Site: modifying date to under 14 days changes style for all events

### ISSUE THREAD

**Issue by Seanland** [Volmarg/personal-management-system#1]
I modified the date in the "My car schedules table" on the demo site.  It changed the styling for all events listed in the table.

Please see the included image.
![Capture](https://user-images.githubusercontent.com/1467495/61732690-2a481e80-ad4c-11e9-93eb-17102d2c7c3f.PNG)

**Comment by Seanland** [comment]
As a note in case it is related, I also changed the "schedule type" to "one-time"

**Comment by Volmarg** [comment]
Thanks for info - will take a look.

**Comment by Volmarg** [comment]
Should be fine now - please take a look in free moment.

**Comment by Seanland** [comment]
Looks good! 

I do not know if you want me to make a new Issue or not, but I just noticed the sorting is done by day of the week prior to month of the year. 

So, for example:
01-05-2019 is before 02-04-2019

**Comment by Volmarg** [comment]
Yeah please make new issue out of it. Let's split each problem in separated thread.
I'm closing this one then.

**Comment by Volmarg** [comment]
And thanks for recheck. :)
