### ISSUE TITLE
Add docker as installation method

### ISSUE THREAD

**Issue by AuthorShin** [Volmarg/personal-management-system#100]
Hello
Can you guys add docker as a installation method?
Thank you

**Comment by Volmarg** [comment]
Hello,

What do You mean?

There is a way to handle this via docker: https://volmarg.github.io/docs/general/installation/docker/information

**Comment by AuthorShin** [comment]
Hello
I meant to have the image added on hub.docker.com so you can install it even via the docker management platforms.

**Comment by ySkNight** [comment]
Would love this add to docker hub as well.

**Comment by cichy45** [comment]
I also support this issue. I run my containers using TS-233 qnap nas and their Container Station. I can create containers using docker-compose files, but I lack further knowledge regarding this platform to perform additional steps like rooting into container to run sh setup script. Also the performance and RAM amount of this unit (2GB) seems too limited for current setup. 
It would be great to see single image possible to setup with docker-compose without the need to run any additional scripts.

**Comment by Suburban-Vampire** [comment]
here's another vote for getting this onto Docker Hub. I personally was all set to try PMS out, but it not being on the hub already makes it a lot less straightforward.

The good part is, it looks like it's not too complicated to sort out this aspect of the project, should the dev(s) decide to do so:

https://docs.docker.com/get-started/04_sharing_app/

**Comment by Volmarg** [comment]
Closing, cuz docker is long there and also might update that over time. Dunno
