### ISSUE TITLE
Exception InvalidFieldNameException thrown upon first run

### ISSUE THREAD

**Issue by g-iori** [Volmarg/personal-management-system#134]
Running on docker/windows

Installed fine, no errors following instructions.

Upon first access it throws the following exception:

`[PDOException](http://127.0.0.1:8001/login#trace-box-3)  [Exception](http://127.0.0.1:8001/login#trace-box-2)  [InvalidFieldNameException](http://127.0.0.1:8001/login#trace-box-1)`

`An exception occurred while executing 'SELECT t0.id AS id_1, t0.password AS password_2, t0.avatar AS avatar_3, t0.nickname AS nickname_4, t0.lock_password AS lock_password_5, t0.roles AS roles_6, t0.email AS email_7, t0.email_canonical AS email_canonical_8, t0.username AS username_9, t0.username_canonical AS username_canonical_10, t0.enabled AS enabled_11, t0.salt AS salt_12, t0.last_login AS last_login_13 FROM app_user t0':`

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.lock_password' in 'field list'`

I assume something is wrong with user register? 
Help is appreciated.

Thanks in advance.

**Comment by NewMasterG** [comment]
another exception but same issue for me. Installation run smooth, no errors. First attempt to navigate to http://mydomain:8001 results in this:

An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.value AS value_3 FROM setting t0 WHERE t0.name = ?' with params ["modules"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pms.setting' doesn't exist


someone?

**Comment by Volmarg** [comment]
Can't really help here because everything works for me, just spawned the fresh instance from container, went in, called first run setup and worked out. `sh docker-first-run.sh`
