### ISSUE TITLE
Integration with calDav, openTask

### ISSUE THREAD

**Issue by TesterEU** [Volmarg/personal-management-system#141]
@Volmarg 
hi,
My attempt to contact the author of the project (you?) was unsuccessful, so I created a topic with a suggestion to add calDav, openTask support in my application. I would be grateful for your answer. My proof:
![scr](https://github.com/user-attachments/assets/918643c5-2345-4ef6-83bf-4be8afaa4dbc)

kind regards
Tester

**Comment by Volmarg** [comment]
Hello,

Yup saw it, but had no time earlier to handle this so same as in response:
- not planning this, as the project is suppose to be "closed from external tools"

I might eventually add export-to-file at some point.
