### ISSUE TITLE
Car Schedule Table: Date Sorting By Day Prior to Month

### ISSUE THREAD

**Issue by Seanland** [Volmarg/personal-management-system#2]
The date in the table is being sorted by day prior to month.

Example:
01-05-2019 is before 02-04-2019

**Comment by Volmarg** [comment]
Yes that's a bug. I will take a look on it near weekend, as this might be more tricky.

**Comment by Volmarg** [comment]
Should be fine now - please recheck in free time.

**Comment by Seanland** [comment]
Sorting seems fine.

Thanks @Volmarg

**Comment by Volmarg** [comment]
Thanks for recheck and reporing as well.
