### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by MohamedElashri** [Volmarg/personal-management-system#36]
Hi, is there any docker image for this project?

**Comment by Volmarg** [comment]
Hello,

There isn't any, but i see more and more and more people asking about it.

I will add it to my list for later but no idea when will i grab it.

**Comment by MohamedElashri** [comment]
Thank you, I'm really looking forward to this move.

**Comment by Volmarg** [comment]
Hello there.

That's rather late response but there is a pull request with docker.

Are You maybe still interested in it?

Would be nice if You could test it in free time as I will be rather able to do it a bit later but I just know that this issue is kept open:
https://github.com/Volmarg/personal-management-system/pull/43

**Comment by MohamedElashri** [comment]
Hello 

Thank you very much. I was still waiting for the docker version. 

I've installed it correctly from the docker branch. I can use all of the functions so far without any problems. 
I think this docker version is working and worth be added to the official project.  Also it would be easier for people  if we can build a version in Docker hub and update it regularly.

**Comment by Volmarg** [comment]
Did You had any issues with maria from this docker image?
As i see there is mariadb configuration.

**Comment by MohamedElashri** [comment]
> Did You had any issues with maria from this docker image?
> As i see there is mariadb configuration.

As far as now with very small entries in some modules. I did not have any problem with mariabdb and I don't subsect any problem as I see a correct link  between the containers. 

> Also seems like the project is running on php7.4 inside docker?
> Can You check php version from within the container?

This is what is used inside the container. PHP 7.4.10 (cli) with Zend Engine v3.4.0

**Comment by Volmarg** [comment]
Can You Also throw some php info in index.php to check the project php version as cli can have other one?

**Comment by MohamedElashri** [comment]
> Can You Also throw some php info in index.php to check the project php version as cli can have other one?

tried this code 
`$version = phpversion();
print $version;

which confirms that the php version is php 7.4.10 from the index.php file. 
`

**Comment by Volmarg** [comment]
Cool. Thx. This means that the project is actually pretty compatible with 7.4, alongside with the updated packages that come with this docker image.

Ok then. I will close this issue, let me know if You will have some project based problems or if it works fine after some more testing. 
I wanted to move to php 7.4 by the end of this year but seems like this might go faster than expected.
