### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by dpieski** [Volmarg/personal-management-system#37]
First, this project looks amazing! I am excited to start messing around with it.

Idea: Do you have a way to do personal inventory / is that in your plans?

Thoughts - It would be useful (at least to me) to have an inventory module so you can have, for example,
Item: Type, Make, Model, S/N, Purchase Date, Purchase Price, Associated Items: Type, Make, Model, PDate, PPrice.

So, for instance:
Type: Refrigerator
Make: Kenmore
Model: 2020VersionModel
S/N: 1234TheSerial#
Associated Item:
Type: Filter
Make: Kenmore
Model: F#4MyFridge

I saw that you have the car info in a Note. So the car could be like:
Type: Vehicle
Make: Subaru
Model: 2018 Crosstrek
SN: MyVIN#
Associated Item:
Type: Oil
Make: Pennzoil
Model: Synthetic 5W30

**Comment by Volmarg** [comment]
Hello,

I don't plan something like this, I got notes for things like that at this point.
I'm balancing between usability/time consumption for something, so I don't see any usage for such thing - right now You could just use notes for this.

If You play with development and want to give a try to build this then i could guide which logic You can reuse as relation between same type of records / parent/child removal check etc. is pretty much there, so 80% is copy + paste ~20% is new thing.

**Comment by Volmarg** [comment]
Closing due to missing response. Reopen if needed.
