### ISSUE TITLE
Dirrecting to demo with https://

### ISSUE THREAD

**Issue by OleMortensen8** [Volmarg/personal-management-system#40]
The Documentation has been observed redirecting people to the demo of the PMS without a proper SSL certificate causing Error in access to the demo.

I'd advice the following action being taken: 

- [ ] Fixed Documentation to redirect to interested party to a http :// .

**Comment by Volmarg** [comment]
I don't uderstand. Where did You found the link?

**Comment by OleMortensen8** [comment]
Apology I said Documentation, I mean The README.md  

"Preview

Fully accessible demo can be found ⇛Here⇚."

**Comment by OleMortensen8** [comment]
somehow I no longer find this issue.
