### ISSUE TITLE
Can't set data like currency

### ISSUE THREAD

**Issue by Lapotor** [Volmarg/personal-management-system#41]
Hello,
today i had set up this panel.
I can login and it runs but for example when i try to enter my currency it just loads and in the console i get this error:
![grafik](https://user-images.githubusercontent.com/17144397/91635202-ce43d500-e9f6-11ea-9f9b-648d494351e6.png)

I tried some of the #33 things but nothing works.
I use a Ubuntu 18.04 server with PHP 7.2.24
In the backlogs i only get package Deprecated infos.

I also changed from node 12 to node 9.
Even with the build in debug viewer i don't get any other error.

I hope you or someone else can help me. :smiley:

**Comment by Volmarg** [comment]
Which branch or release are You using?

**Comment by Lapotor** [comment]
Hey,
i use v1.3a.
I followed the steps from the installation guide.
The i started the server as described.

After that i go to the IP address and logged me in.
Then i clicked on the top on the profile -> Settings.
Scrolled down to currency added:
|Filled|
|:---:|
|Euro|
|€|
|1|
| Default |

Then it just load and throw the error.

**Comment by Volmarg** [comment]
Ok will take a look on free time.

This might be a bug since in 1.3a js has been completely rebuilt.

**Comment by Volmarg** [comment]
Fixed in **[1.3a.1](https://github.com/Volmarg/personal-management-system/releases/tag/v1.3a.1)** - please retest it with this version

**Comment by Volmarg** [comment]
No response - closing.
