### ISSUE TITLE
composer's hash changed

### ISSUE THREAD

**Issue by ThellraAK** [Volmarg/personal-management-system#45]
Using docker-compose and 

ERROR: Service 'php-fpm' failed to build : The command '/bin/sh -c php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"     && php composer-setup.php --filename=composer     && php -r "unlink('composer-setup.php');"     && mv composer /usr/local/bin/composer' returned a non-zero code: 1

I downloaded the https://getcomposer.org/installer file and the sha384 hash is now

c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394

**Comment by ThellraAK** [comment]
https://github.com/Volmarg/personal-management-system/commit/79609ab83aa5120a3dd0c28da3cb255c0e76af49

Fixed it and got it going on my system.

**Comment by Volmarg** [comment]
Hey there,

Will take a look on this at weekend as I will be releasing new version with Symfony5 support.

**Comment by Volmarg** [comment]
This will have to wait a bit as i want to update the new documentation up to the point where it at least equals the old one with content before i make the S5 release.

**Comment by Volmarg** [comment]
Sadly I'm unable to test that as I've pretty much like 1mb limited connection and this isn't going to change anytime soon. Could You maybe retest it and let me know if this is still up to date? I will just make the change in my repository since I'm unable to handle that.

**Comment by insajd** [comment]
Hey, I had same issue and I can confirm that this pull fixes issue regarding composer-setup.php hash

**Comment by Volmarg** [comment]
@ThellraAK Thanks for providing the fix, since there was no pull request, I've just copied it.
@insajd Thanks for info

I've updated the `main` with the hash.
