### ISSUE TITLE
composer.lock file locking for php 8.0

### ISSUE THREAD

**Issue by jvitali** [Volmarg/personal-management-system#48]
Im currently trying to run pms on Ubuntu 16.04 with php 7.4.13 from main branch.

When running composer install everything installs without issues, but when I ran bin/console cache:clear command and every command involving symfony the following message is displayed:

Fatal Error: composer.lock was created for PHP version 8.0 or higher but the current PHP version is 7.4.13.

**Comment by Volmarg** [comment]
Thanks, will take a look on this - had the same issue, thought that it happens due to having php8.0 and php7.4 at same time locally.

**Comment by jvitali** [comment]
I completely remove php from my test environment and re installed php7.4 alone to test it and still happening.
let me know if you need specific command outputs, I will post it here.

**Comment by Volmarg** [comment]
Can You call `composer dump-autoload` and then retry?

**Comment by jvitali** [comment]
Still getting this if statement on vendor\autoload.php:

```
if (\PHP_VERSION_ID < 80000) {
    echo sprintf("Fatal Error: composer.lock was created for PHP version 8.0 or higher but the current PHP version is %d.%d.%d.\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION, PHP_RELEASE_VERSION);
    exit(1);
}
```

**Comment by Volmarg** [comment]
Yeah I've got the solution.... I had totally no idea that `symfony.lock` somehow controlls the `composer` logic. Will push the fix later / tommorow.

Atm. You can edit Your `symfony.lock` file.
Search for `    "php": {` in the file, change to `7.4`.
Remove `vendor`.
Call `composer install`.

Please let me know if the project works fine with that - if You can. I'm pretty much exhausted today so no chance for any testing. However i was able to open the login page with this.

Looks like I learned something new again.

**Comment by jvitali** [comment]
So far with that change it works great!

Thank you for the quick help!

**Comment by Volmarg** [comment]
Fixed in: https://github.com/Volmarg/personal-management-system/commit/f679a5ac2fe54afef460f02f304f411e48a0781c

Closing thread, as this seems to be the issue - nothing else changed in the `composer` files, also login panel / dashboard works fine now.
