### ISSUE TITLE
Migrations errors

### ISSUE THREAD

**Issue by jvitali** [Volmarg/personal-management-system#49]
Running bin/console doctrine:migrations:migrate

Migrating up to 20201115052559 from 20200705090755

**ERROR** Migration 20200912025220 failed during Execution. Error An exception occurred while executing 
**ERROR MESSAGE: **

` INSERT INTO my_todo(`module_id`, `name`, `description`, `deleted`, `completed`, `display_on_dashboard`)
            (
                SELECT
                m.id,
                g.name,
                g.description,
                g.deleted,
                g.completed,
                g.display_on_dashboard
                
                FROM my_goal g

                JOIN module m
                ON m.name = 'My Goals'
                
                GROUP BY g.id
            )
        ':

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pms.m.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

fixed replacing `GROUP BY g.id` to `GROUP BY g.id, m.id`

That fix the rest of the migration script.
This was causing Todo list to crash the app by passing null values.
(Couldn't test if disable ONLY_FULL_GROUP_BY from MySQL will fix this)

**Comment by Volmarg** [comment]
Did You tried this : https://volmarg.github.io/docs/general/known-issues#cant-loginsql_mode?

**Comment by jvitali** [comment]
I haven't change the sql_mode from my.cfg
Instead ran this on my mysql server:
`mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

but seems to be the same solution :)

**Comment by Volmarg** [comment]
@jvitali I think that this is only valid as long as Your mysql server won't be restarted.

**Comment by jvitali** [comment]
You are right!
Restarted my MySQL server and the config was gone. 
Adding sql_mode config to my.cnf is the way!
