### ISSUE TITLE
Prevent password change on demo

### ISSUE THREAD

**Issue by gpoussel** [Volmarg/personal-management-system#5]
I just noticed that the "admin" password has been changed on the demonstration site.
It makes the demo site unavailable for one day, while you're on Hacker News frontpage ;-)

**Comment by Volmarg** [comment]
Oh..

Im sorry guys... Someone was playing dirty then... Will fix near night after work :/

**Comment by Volmarg** [comment]
I reverted it from. Ssh mobile. Login works. Now. But yes need to block that.

**Comment by Volmarg** [comment]
I keep my terminal open just in case before i Block that today even by hardcoding lol.

**Comment by PhilippCl** [comment]
I think the password was changed again. I can't login with admin admin

**Comment by Volmarg** [comment]
Ppl are amazing I will need to protect upload update badly...

Reverted You should be Able to login now.
But i cant open demo on browser to check it, no idea why.

**Comment by Volmarg** [comment]
At this moment I've just removed password field - will do something with env (DEMO = true) once i got some more time.

**Comment by Volmarg** [comment]
Fixed.
Implemented small functions to check if app is in demo mode. This way I can add/remove certain parts of code 
````
if( isDemo() )
....
````
