### ISSUE TITLE
Unable to run PMS using Docker on Windows

### ISSUE THREAD

**Issue by rwaight** [Volmarg/personal-management-system#52]
Greetings!  I am trying to run PMS using Docker on Windows, but am running into some issues that appear to be related to the [PHP APCu Extension](https://volmarg.github.io/docs/general/known-issues/#php-apcu-extension).  I started to document the steps and commands in [this readme](https://github.com/rwaight/personal-management-system/blob/main/docker/README.md), but am at a point where I need help to get PMS to work using Docker on Windows.

In addition to the documentation, I found an excellent write-up in https://github.com/Volmarg/personal-management-system/pull/43#issue-493755082 to get me started.  (On a separate note, I would be willing to help with documentation updates, but would like to know if opening another issue in this repo is how you want to track documentation updates.)

Here are some of my questions:
1. What container needs to have APCu installed?  Is it the `php-fpm` container?
2. Does `pecl install apcu` need to be run before `composer pms-installer-docker` ?
3. If `apcu.ini` needs to exist and have specific content in it, can the project be updated to include the file and needed content?
4. Based on the output I receive, it looks like `"extension=apcu.so"` needs to be added to `php.ini`, can this be added to the project?
5. What else do I need to change to get PMS to work using Docker on Windows?

At a high level, here are the commands I ran:
* in PowerShell
```
docker-compose build
docker-compose up -d
docker-compose exec php-fpm bash
```
* in the php-fpm container
```
composer install
composer pms-installer-docker
pecl install apcu
```

I am using Docker on Windows 10 (using the WSL 2 based engine).  Here are the commands I ran (summary of output):
*note*: the directory is `C:\docker\personal-management-system-1.4.30-attempt03` but i've truncated the output to show `PS C:\docker\pms-1.4.30>`
```
PS C:\docker\pms-1.4.30> write-host 'following steps in https://github.com/Volmarg/personal-management-system/pull/43#issue-493755082'

PS C:\docker\pms-1.4.30> write-host 'also following documentation from https://volmarg.github.io/docs/general/installation/'

PS C:\docker\pms-1.4.30> write-host 'i have not made any changes to the docker-compose file or any other files'

PS C:\docker\pms-1.4.30> docker-compose build

PS C:\docker\pms-1.4.30> docker-compose up -d

PS C:\docker\pms-1.4.30> docker-compose exec php-fpm bash

root@672bcf287a87:/application# sudo composer install
# received `bash: sudo: command not found`

root@672bcf287a87:/application# composer install

root@672bcf287a87:/application# composer pms-installer-docker
## multiple times I am seeing `  APCu is not enabled.` from the output

root@672bcf287a87:/application# pecl install apcu

root@672bcf287a87:/application# apt install php-apcu

root@672bcf287a87:/application# find / -name php.ini

root@672bcf287a87:/application# cat /usr/local/etc/php/conf.d/php.ini

root@672bcf287a87:/application# echo 'going to stop and restart the containers to see if anything is working'

PS C:\docker\pms-1.4.30> write-host 'starting the pms containers again, will check to see if pms works now'

PS C:\docker\pms-1.4.30> docker-compose exec php-fpm bash

root@672bcf287a87:/application# composer pms-installer-docker
## still receiving `  APCu is not enabled.` from the output, assuming because APCu is not enabled in `php.ini`
```

I uploaded the output details to [this gist](https://gist.github.com/rwaight/91b0d47128059f44d1bd660c5699c606) since it was too long to fit in a comment.

Any help would be greatly appreciated!  Also, please let me know if I can assist with documentation updates.

**Comment by Volmarg** [comment]
Hello,

Seems like it's something bigger.
Generally I'm not very familiar with docker, but without really jumping inside the issue, I can write this:

- You need the apcu in the `php-fpm` container (assumptions due to docker):
- it doesn't really matter when You install the `apcu` it's just required later on to make the caching work,
- did You tried this step https://volmarg.github.io/docs/general/known-#php-apcu-extension ?

I see that You tried to modify the  `php.ini`, I know I had some issues therefore I wrote the info about `apcu.ini`

Sorry for not answering the points directly, I do this that way normally but like I've wrote I didn't delved into the issue to much atm. only small analysis.

**Comment by rwaight** [comment]
No worries, thanks for responding @Volmarg.  I _believe_ I have a fix for this, but want to test the configurations on another platform first.  Do you mind if I submit a PR to add instructions for Docker, as well as an update to the `docker\php-fpm\php.ini` file?

Regarding updating `apcu.ini`, I was not able to install `php-apcu` within the `php-fpm` container.  Here is the output when I tried the fix mentioned on the [known issues](https://volmarg.github.io/docs/general/known-issues#php-apcu-extension) page:
```
root@a719234ab9a1:/application# apt install php-apcu
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php-apcu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php-apcu' has no installation candidate
```

With that said, I do have PMS running using Docker on Windows, but I do want to replicate this using Docker on Mac to make sure the commands/updates are valid.

**Comment by Volmarg** [comment]
Interesting, I have the apcu module available on the server with demo version and locally. It might be that I've forgotten some step, but yeah sure You can create a merge request with instruction for docker.

I will add the docker instruction to the documentation since I generate it locally in documentation builder.

**Comment by Volmarg** [comment]
In the worst case the apcu can be turned off in
```
https://github.com/Volmarg/personal-management-system/blob/main/config/packages/doctrine.yaml
```

should be just enought to remove the

```yaml
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.apcu
            doctrine.system_cache_pool:
                adapter: cache.adapter.apcu
```

**Comment by rwaight** [comment]
@Volmarg I've submitted https://github.com/Volmarg/personal-management-system/pull/55 to update the project and resolve this issue.  Please let me know if any adjustments need to be made, thanks!

**Comment by Volmarg** [comment]
@rwaight https://github.com/Volmarg/personal-management-system/commit/ce7694bbf7f8094077d13f6f742cc13fdce5ddcf

Thx for providing the informations.
