### ISSUE TITLE
Blank Page on Install

### ISSUE THREAD

**Issue by henrisja** [Volmarg/personal-management-system#59]
Hello,

This project looks awesome so far, but I am trying to set it up and am running into an issue after running the composer pms-installer and trying to access the page which I haven't seen brought up in the [Known Issues](https://volmarg.github.io/docs/general/known-issues/). I'm running this on a Raspberry Pi 4 and have followed all the instructions from the Raspberry Pi installation guide. After everything is installed and I start the symfony server I am just seeing a blank page and am getting back an empty 200 response from the server. In the logs everything looks normal on the web server side, but I see the following stack trace when I try to load the page:
```
[PHP-FPM    ] NOTICE: PHP message: PHP Warning:  Uncaught ReflectionException: Class "Doctrine\Common\Persistence\ObjectManager" not found while loading "App\DataFixtures\FilesTags". in /var/www/personal-management-system/vendor/symfony/config/Resource/ClassExistenceResource.php:181
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 [internal function]: Symfony\Component\Config\Resource\ClassExistenceResource::throwOnRequiredClass()
[PHP-FPM    ] #1 /var/www/personal-management-system/src/DataFixtures/FilesTags.php(10): spl_autoload_call()
[PHP-FPM    ] #2 /var/www/personal-management-system/vendor/composer/ClassLoader.php(478): include('/var/www/person...')
[PHP-FPM    ] #3 /var/www/personal-management-system/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
[PHP-FPM    ] #4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
[PHP-FPM    ] #5 [internal function]: spl_autoload_call()
[PHP-FPM    ] #6 /var/www/personal-management-system/vendor/symfony/config/Resource/ClassExistenceResource.php(84): class_exists()
[PHP-FPM    ] #7 /var/www/personal-management-system/vendor/symfony/dependency-injection/ContainerBuilder.php(348): Symfony\Component\Config\Resou in /var/www/personal-management-system/vendor/symfony/config/Resource/ClassExistenceResource.php on line 181
[PHP-FPM    ] NOTICE: PHP message: PHP Fatal error:  Could not check compatibility between App\DataFixtures\FilesTags::load(Doctrine\Common\Persistence\ObjectManager $manager) and Doctrine\Common\DataFixtures\FixtureInterface::load(Doctrine\Persistence\ObjectManager $manager), because class Doctrine\Common\Persistence\ObjectManager is not available in /var/www/personal-management-system/src/DataFixtures/FilesTags.php on line 13
```

I started the symfony server with the command `symfony server:start --port=8001 -d` and am trying to access the web page from another computer on the same network via the local IP address of the pi which I think should be fine. Any guidance would be appreciated here, let me know if any more detail would be helpful.

I know that this is a project made and maintained by one person so this may not be a high priority, but it looks really cool and I'd like to start using it 💯

**Comment by Volmarg** [comment]
Hello,

I've made changes right now in the `DataFixtures` - this is visible in the call stack, and there was indeed a wrong class. Might've been working for my due to some older packages present in `vendor`. Update Your local version from `master` and try again.

**Comment by Volmarg** [comment]
@henrisja last call before i will close this due to missing reponse

**Comment by jcdescy** [comment]
Greetings, I get a blank page as well. I followed the installation instructions and just called /installation.php which doesn't exist. When I call /public/installation.php I get a blank looking page. Here's a screenshot of the source code of that page. 
<img width="1104" alt="grafik" src="https://user-images.githubusercontent.com/3777842/193564951-7a601895-c9da-4019-8fb7-3fef847e2a39.png">
