### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by capriciousduck** [Volmarg/personal-management-system#60]
How to host this app on heroku?

**Comment by Volmarg** [comment]
I've played with Heroku only once,
Doesn't it just consist of some CLI command which allows You to push data on the server? Or somewhat login on the server via CLI and pulling the REPO?

From there You should be able to do the whole installation i believe. At least I've deployed React thing once there and all I had to do was pushing files from local system.

Out of this I never used heroku any more.
I just took small 15s look on the: https://devcenter.heroku.com/articles/git#prerequisites-install-git-and-the-heroku-cli .

I think I did it the same way back then.

**Comment by capriciousduck** [comment]
Ok. Where is the data stored? In a database? or in a directory on the server?

**Comment by Volmarg** [comment]
It's a database (MySQL/MariaDB - preferred MySQL): https://volmarg.github.io/docs/general/installation/general#creating-database

**Comment by capriciousduck** [comment]
I want to run the app on heroku. Where do I put in the database credentials manually?

**Comment by Volmarg** [comment]
`.env` -> `DATABASE_URL`

**Comment by capriciousduck** [comment]
Ok
