### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [Volmarg/personal-management-system#64]
Hello,

We recently received a vulnerability disclosure from @ranjit-git against your repository. I couldn't find a security policy or contactable e-mail to share the vulnerability details with you.

If you can provide me with an e-mail, I can send it over to you? Otherwise, you can view the advisory [here](https://huntr.dev/bounties/1-other-Volmarg/personal-management-system/).

It is private to only you and the discloser. If you have any questions, here to help!

-- Jamie from huntr.dev

**Comment by Volmarg** [comment]
Hello, 

You can send me the information on the E-mail: `dwlodarczyk13@tlen.pl`
Do let me know after sending it.

**Comment by ranjit-git** [comment]
@Volmarg  sent report details to dwlodarczyk13@tlen.pl

**Comment by Volmarg** [comment]
Hah nice,

While I get Your point - this should never actually happen because the idea of my project is that "it's only for You", and like I mentioned in few places (also in documentation) such verification are not there because I had to pick between functionality and better quality - I choose to balance this as I worked on the project alone (time wise best option).

Still I wonder why this happens so gonna check that out in free time out of curiosity.

**Comment by ranjit-git** [comment]
@Volmarg 
thanks for taking a look into this issue .
Can you plz update the report status(valid/invalid) here https://huntr.dev/bounties/1-other-Volmarg/personal-management-system/ so that huntr can gives bounty to researcher ?

Thanks again

**Comment by Volmarg** [comment]
Sure I will get to it once I will have time to sit down and think about that - I keep that in mind, just being to busy recently.

**Comment by Volmarg** [comment]
Well... I cannot recreate this at all. Just tried it out few times. Would need the exact string that is passed to input.

**Comment by ranjit-git** [comment]
Payload is ```xss"'><img src=x onerror=alert()>```

**Comment by Volmarg** [comment]
Generally I cannot consider this security issue. Naturally this should not happen in some globally available project. This is only project for private usage.

Fixing it took me 10 min so why not: https://github.com/Volmarg/personal-management-system/commit/b8614509957dbda6a81fbbc4bc8960bdbc251280

I confirm that this issue existed but I will not add confirmation on the page that You pointed (unless I can register without github account and seems like i cant) - I don't like how fish this website looks like. 

So if there is other way to register then let me know.

**Comment by ranjit-git** [comment]
Yes, they have a magick link .
Using that link you can validate the report without signup .
Let me ask them to sent you the magick link

**Comment by JamieSlome** [comment]
@ranjit-git @Volmarg - I have processed a magic link and it should be sent over to `dwlodarczyk13@tlen.pl` within the next hour.

Thanks! 🎉

**Comment by Volmarg** [comment]
Got no email so far.

**Comment by JamieSlome** [comment]
@Volmarg - just checked our e-mail service, it was definitely sent out.

Can you check your other e-mail folders, perhaps in promotions?

**Comment by Volmarg** [comment]
Is there any special string for which I should maybe look on whole mail?

**Comment by JamieSlome** [comment]
`the content can be accessed via the magic link below` - try this! @Volmarg

**Comment by Volmarg** [comment]
Done

**Comment by JamieSlome** [comment]
Great! @Volmarg - are you able to mark it as valid and confirm the patch?

**Comment by Volmarg** [comment]
done

**Comment by ranjit-git** [comment]
hi, @Volmarg 
Reported two more security bug in this repo .
You should have  already received the magick link via mail to view the details . 
Plz check when you have time
