### ISSUE TITLE
apcu.so not found

### ISSUE THREAD

**Issue by EtherealMochi** [Volmarg/personal-management-system#71]
Hey first I wanted to say that I appreciate you sharing this with us! I cant wait to use it. 

I installed it on windows initially in WSL/docker and had no issues but when I tried running docker-compose build on my raspberry pi I kept getting **apcu.so not found**. I don't know if anyone else had this issue but I had to swap 2 of the lines in your Dockerfile for php-fpm to get it to work. 

26 COPY php.ini /usr/local/etc/php/conf.d/php.ini

28 RUN pecl install apcu

became: 

26 RUN pecl install apcu

28 COPY php.ini /usr/local/etc/php/conf.d/php.ini

and the build completed fine. Not really sure why it worked on WSL/docker but not on the pi4 with docker. Mainly just posting here incase other people have issues and are trying to figure it out.

**Comment by Volmarg** [comment]
hello,
thx, I can either update documentation with this or add docker file for rapberry.

**Comment by EtherealMochi** [comment]
Great! Thank you!
