### ISSUE TITLE
Error in query (1071): Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by EtherealMochi** [Volmarg/personal-management-system#72]
I have a working install on docker-windows through WSL. I am working on setting this up on a raspberry pi 4 which it was initially working fine. I can get it to install on my pi4 through docker but for some reason it is no longer populating the database. I have redownloaded the release and started fresh, following the steps in your documentation but issue still remains. I backed up the working database on my WSL to try and import to the database on my pi4 docker install. Now when importing the working database backup I am getting this error:

![image](https://user-images.githubusercontent.com/51897953/128730210-b141bdd4-1082-48d5-9777-cae589f08f5d.png)

which leads me to believe that this is why the database is not working during initial setup. I have tried some google-fu but have been unable to locate a working solution. Do you have any suggestions on what I can do?

**Comment by EtherealMochi** [comment]
Ok that stopped the error on that file version but now I am getting it on a different one. 

Migration 20191110042650 failed during Execution. Error An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_DCD489F05E237E06 ON my_contact_type (name)':

SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes

I changed that file to all 50 on VARCHAR and it didnt work. I am using the linuxserver/mariadb since I am running arm32 not arm64.

**Comment by Volmarg** [comment]
I doubt it's a power outtake. Sounds more as a DB engine / version / configuration.

Strangely didn't had this issue on Mysql (locally) and neither on Maria (raspberry).

So I understand correct - it works fine now?

What Maria version did You had before and got now? Just out of curiosity to see what's the case.

**Comment by EtherealMochi** [comment]
> I doubt it's a power outtake. Sounds more as a DB engine / version / configuration.
> 
> Strangely didn't had this issue on Mysql (locally) and neither on Maria (raspberry).
> 
> So I understand correct - it works fine now?
> 
> What Maria version did You had before and got now? Just out of curiosity to see what's the case.

no unfortunately its still not working. Are there any logs that could give insight to whats happening?
