### ISSUE TITLE
Podman NGINX Container FastCGI Connection Refused Error

### ISSUE THREAD

**Issue by Zanathoz** [Volmarg/personal-management-system#85]
I've been trying to set this up on my Fedora 34 environment for the past few days using Podman. After resolving some DNS issues related to keeping the NGINX container online (running PiHole on the same server, I could not resolve the DNS of mariadb), all the containers are now online. I'm now getting a 504 Bad Gateway error when browsing to the http://192.168.0.200:8001 webpage with the following error from the nginx container output:

2022/01/23 14:13:27 [error] 26#26: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.125, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.200:9000", host: "192.168.0.200:8001"
2022/01/23 14:13:28 [error] 26#26: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.125, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://192.168.0.200:9000", host: "192.168.0.200:8001", referrer: "http://192.168.0.200:8001/"

192.168.0.125 is my laptop on network. I was running Portainer on port 9000 previously and have since move it to port 9005. I also removed Portainer completely before trying a new build of the project again with the same issue happening.

The same for Bookstack which uses a mariadb container. I removed this completely as well in the event PMS needs 9000 and 3306 explicitly in other parts of its configuration.

I've tried changing the EXPOSE port in the Docker file for fpm-php to 9001 and the lookup port in the Nginx.conf.d file to 9001 to match while Portainer was removed, but that results in no webpage displaying at all after a new build is pushed.

Here is my docker-compose file and a log of a fresh build with no database built in the repository.
version: "3.1"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment: 
      - MYSQL_DATABASE=pms
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - /var/mynfsshare/data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    working_dir: /application
    volumes:
      - /var/mynfsshare/:/application
      - /var/mynfsshare/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"

  php-fpm:
    build: ./docker/php-fpm
    container_name: php-fpm

    restart: unless-stopped
    working_dir: /application
    volumes:
      - /var/mynfsshare/:/application

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

[build.log](https://github.com/Volmarg/personal-management-system/files/7920710/build.log)

The build log contains a lot of extra special characters for some reason, sorry about that.

The same results happen when using podman-compose or docker-compose commands. Podman now has docker compatibility built into it, so I do not think this is a podman/docker incompatibility issue but I could be wrong. I do have a spare Fedora VM I can try this on or spin a new one up but I feel I've hit a wall here.

 The only thing that pops out to me at the moment is this from the first-run docker script within the php-fpm container:
Continue as root/super user [yes]? 
> php -r "include_once 'installer//AutoInstaller.php'; use Installer\AutoInstaller; AutoInstaller::runDocker();" < /dev/tty

[0;34m=================================================================================[0m
**sh: 1: node: not found
sh: 1: npm: not found
sh: 1: mysql: not found**

I also allowed ports 8001 and 9000 through the SElinux firewall in the event that was an issue with the same result.

Any assistance with this or should I just spin this up without docker/podman on a different server? I'd like to keep all files on an NFS share for backup purposes and would rather keep it containerized for upgrading if possible.

**Comment by Volmarg** [comment]
I barely know anything about docker, build / configuration was prepared by one of the contributors.

But do I get it correctly that You also tried it directly in docker and it failed?

**Comment by Zanathoz** [comment]
Yes that's correct. I tried "docker-compose build" and "docker-compose up -d" and it still failed with the same behavior. This is after clearing out all images and building fresh between each attempt.

I was away on business the past few days but I can try this on a fresh Fedora server tomorrow. I can also try Ubuntu or Debian fresh to see if this is a Fedora\Podman issue directly.

Podman is replacing docker (eventually) so I think it would be worth investigating if it is a podman issue.

**Comment by Volmarg** [comment]
Try ubuntu maybe then? It worked fine for me on 18.x / 20.x

**Comment by Zanathoz** [comment]
Ok, I'll try and report back, have not had time due to emergency issue at work.

**Comment by Zanathoz** [comment]
I installed a fresh Fedora 35 environment this morning and installed the appropriate docker components needed to get podman compatible:

dnf install docker-compose
dnf install podman-compose
dnf install podman-docker

Once those were working, I ensured podman and docker were working harmoniously:

sudo systemctl start podman.socket
sudo curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping

I then ran through your docker install and I'm now able to get to the registration/login splash page, so there must be something wrong with my Fedora 34 environment (I blame the local pihole/DNS container as always).

I'm going to dig a bit more on my end and try to break my Fedora 35 environment now to see what caused the issue, but I think we can close this one out. Thanks for what looks to be (I've yet to use) an awesome project!

**Comment by Zanathoz** [comment]
Coming back to post that I found out pihole is the culprit here. It's using port 53, and during the docker-compose sequence and new pms_default network is created. 

In this networks configuration file is some base dnsmasq configuration and causes port 53 to overlap and the pihole container cannot run at the same time as the nginx container. It seems that's the only portion of the project affected by this.

I even tried moving these containers over to my bridge network with my main containers as a test and the same behavior occurs. Either way, as always DNS is the culprit. I'll just have to run this on a separate VM, or perhaps it's time to move pihole over to a dedicated device!

**Comment by Volmarg** [comment]
Good luck with setting it up.
